display_name: FlClash
package_name: flclash
maintainer:
  name: chen08209
  email: chen08209@gmail.com

licenses:
  - GPL-3.0-or-later

installed_size: 6604
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator
  - libkeybinder3

keywords:
  - FlClash
  - Clash
  - ClashMeta
  - Proxy

generic_name: FlClash

categories:
  - Network

startup_notify: true
startup_wm_class: com.follow.clash
