display_name: FlClash

packager: chen08209
packagerEmail: chen08209@gmail.com
license: GPL-3.0-or-later

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

auto_req: false

requires:
  - libappindicator-gtk3
  - keybinder3

keywords:
  - FlClash
  - Clash
  - ClashMeta
  - Proxy

generic_name: FlClash

categories:
  - Network

group: Applications/Internet

startup_notify: true
startup_wm_class: com.follow.clash
