display_name: FlClash
package_name: FlClash
maintainer:
  name: chen08209
  email: chen08209@gmail.com

priority: optional
section: net
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-1
  - libkeybinder-3.0-0

keywords:
  - FlClash
  - Clash
  - ClashMeta
  - mihomo
  - Proxy

generic_name: FlClash

categories:
  - Network

startup_notify: true
startup_wm_class: com.follow.clash
