// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `authenticate_server`, `call_helper`, `helper_path_from_app_path`, `helper_service_pid`, `is_valid_session_id`, `process_image_path`, `read_frame`, `write_frame`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HelperRequest`, `OwnedServiceHandle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `drop`, `fmt`

Future<HelperRpcResponse> helperPing() =>
    RustLib.instance.api.crateApiHelperHelperPing();

Future<HelperRpcResponse> helperStartCore({
  required String address,
  required String sessionId,
}) => RustLib.instance.api.crateApiHelperHelperStartCore(
  address: address,
  sessionId: sessionId,
);

Future<HelperRpcResponse> helperStopCore({required String sessionId}) =>
    RustLib.instance.api.crateApiHelperHelperStopCore(sessionId: sessionId);

class HelperRpcResponse {
  final bool ok;
  final String? sessionId;
  final int? corePid;
  final bool? stopped;
  final String? reason;
  final String? code;
  final String? message;

  const HelperRpcResponse({
    required this.ok,
    this.sessionId,
    this.corePid,
    this.stopped,
    this.reason,
    this.code,
    this.message,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      sessionId.hashCode ^
      corePid.hashCode ^
      stopped.hashCode ^
      reason.hashCode ^
      code.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HelperRpcResponse &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          sessionId == other.sessionId &&
          corePid == other.corePid &&
          stopped == other.stopped &&
          reason == other.reason &&
          code == other.code &&
          message == other.message;
}
