// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `authenticate_server`, `call_helper`, `helper_service_pid`, `read_frame`, `write_frame`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HelperRequest`, `HelperResponse`, `OwnedServiceHandle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

Future<String> helperPing() => RustLib.instance.api.crateApiHelperHelperPing();

Future<int> helperStartCore({required String arg}) =>
    RustLib.instance.api.crateApiHelperHelperStartCore(arg: arg);

Future<void> helperStopCore() =>
    RustLib.instance.api.crateApiHelperHelperStopCore();
