// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `available_read_len`, `cleanup_socket`, `finish_server`, `io_loop`, `is_current_gen`, `is_nonblocking_idle`, `join_server`, `make_frame`, `poll`, `prepare_socket`, `report_error`, `reset`, `secure_socket_permissions`, `server_active`, `stop_server_thread`, `take_server_handle`, `validate_client_pid`, `validate_frame_len`, `validate_peer_identity`, `wait_for_authorized_peer`, `windows_pipe_available_bytes`, `write_all_interruptible`, `write_frame`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FrameReader`, `PeerIdentity`, `ServerState`, `WindowsPipeReader`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `eq`, `fmt`, `read`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<void> setExpectedCorePid({required int pid}) =>
    RustLib.instance.api.crateApiIpcSetExpectedCorePid(pid: pid);

Future<void> clearExpectedCorePid() =>
    RustLib.instance.api.crateApiIpcClearExpectedCorePid();

Stream<Uint8List> restartIpcServer({required String name}) =>
    RustLib.instance.api.crateApiIpcRestartIpcServer(name: name);

Future<void> stopIpcServer() => RustLib.instance.api.crateApiIpcStopIpcServer();

Future<bool> ipcServerStatus() =>
    RustLib.instance.api.crateApiIpcIpcServerStatus();

Future<bool> isIpcConnected() =>
    RustLib.instance.api.crateApiIpcIsIpcConnected();

Future<void> sendIpcMessage({required List<int> data}) =>
    RustLib.instance.api.crateApiIpcSendIpcMessage(data: data);
